### ISSUE TITLE
Database columns/results are case-sensitive.  

### ISSUE THREAD

**Issue by tlorens** [jackalope/jackalope-doctrine-dbal#173]
We're on an oracle database and all columns are upper case.  There's code in Client.php that iterates through arrays using lower-cased keys.  This obviously blows up  when results are upper-cased.  I've patched the code with a simple call to :  $row =array_change_key_case($row, CASE_LOWER); in a few spots.   You make the call on a better, more practical solution.

**Comment by jjwdesign** [comment]
@dbu

I know this is a very old thread, but I'm going to look at making a PR for this change soon. I've recently forked this project and will make a few fixes for Oracle. The majority of the problems we are facing are case related.

I tried to add some middleware to our document manager factory class, but it only helps with certain issues.

```        $dbConfig = new ConfigurationDBAL;
        $dbConfig->setMiddlewares([
            new Middleware(ConnectionPortability::PORTABILITY_FIX_CASE, ColumnCase::LOWER)
        ]);
        // create a doctrine dbal connection
        $dbConn = DriverManager::getConnection($dbParams, $dbConfig);
```
How long do you think it would take to review a PR for this update and get the changes included? Maybe in a Dev branch we can test with? We are doing a huge code migration to Laminas and PHP 8+. As usual, we're on a strict timeline and a bit behind.

**Comment by dbu** [comment]
hi, old indeed... but still valid as oracle does not go away :-D 

i am glad if you take this up. i would expect that if we make all places that construct queries respect the lower/upper case defined in [the schema](https://github.com/jackalope/jackalope-doctrine-dbal/blob/baeb69776f60a64a882513566ec727854968bbbf/src/Jackalope/Transport/DoctrineDBAL/RepositorySchema.php), we would not need any middleware to make this work, right? or is it more complicated than that?

in terms of BC, i am a bit torn between adjusting the schema case to match the code or the code to match whats in the schema. but afaik for all officially *currently* supported databases the case does not matter, so i'd rather keep the schema the same and adjust the places where we query. (if somebody edited their oracle schema after setting up jackalope to match the case in the code but did not contribute back the fixing, they will have to revert the schema to what it is supposed to be...)

for the process: i don't have any longer holidays planned, so i should be able to react relatively quickly. however, to do the pull request you will fork this repository anyways, and you can make composer use your fork until i merged and tagged a release. set up your fork as a repository in composer.json (and then adjust the require part to say `jackalope-doctrine-dbal: dev-your-branch-name`) and update dependencies with that.

```
    "repositories": [
        {
            "type": "git",
            "url": "git@github.com:your-fork/jackalope-doctrine-dbal.git"
        }
    ]
```

**Comment by jjwdesign** [comment]
@dbu Thank you for the quick and helpful response.

Concerning the schema casing issues: The middleware only helped with a small portion of the casing issues. Our Oracle DB is all in UPPER_CASE; field and table namings. I think most are. That's fine for Oracle, but presents problems for PHP. We are using PHP OCI8 extension and not the PDO Oracle extension. I think there was some dependency issue there. If we could use the PDO Oracle extension, then we could set the casing using the PDO option PDO:CASE_LOWER. Then all field naming would be lower cased. Unfortunately, other packages require the PHP OCI8 extension.

```
$options = [
    PDO::ATTR_CASE => PDO::CASE_LOWER,
];
$connection = new PDO($dsn, $username, $password, $options);
```

```Oracle is not case sensitive about column names. From the meta data, the column names are ALWAYS in upper case. There is nothing to worry about. That is how oracle does it.```
I wish there was nothing to worry about. Ha! :)

Concerning the GIT: Thank you for all of the information. I have forked the project to: jjwdesign/jackalope-doctrine-dbal . Unfortunately, our DevOps team will not install Git on the Linux servers (OpenSUSE), so I'm still stuck relying on your project from packagist.org.

**Comment by jjwdesign** [comment]
@dbu  I went ahead and forked the project and made a PR today. For now we are using my github fork.

We don't have git installed on the server (security). So, this composer.json change did the trick.

```
{
	"type": "vcs",
	"url": "https://github.com/jjwdesign/jackalope-doctrine-dbal.git"
}
```

**Comment by jjwdesign** [comment]
@dbu Ok, false alarm. I finally got to the bottom of this issue. There were 4 or 5 other sessions/connections being made in the controllers <shaking head>. So, the setMiddlewares() was working on my one document manager session, but there were other sessions created that did not use the middleware. So, it works. We don't need to add anything to the code.

**Comment by dbu** [comment]
#401 implements automatically registering the compatibility plugin to lowercase things that oracle messes up when the platform is identified as oracle.
