### ISSUE TITLE
Auto-creation of child node is not yet supported in DoctrineDBAL transport.

### ISSUE THREAD

**Issue by dantleech** [jackalope/jackalope-doctrine-dbal#187]
https://github.com/jackalope/jackalope-doctrine-dbal/blob/master/src/Jackalope/Transport/DoctrineDBAL/Client.php#L1597

Any hints on how to implement this?

**Comment by dbu** [comment]
fixed in https://github.com/jackalope/jackalope-doctrine-dbal/pull/188
