### ISSUE TITLE
validate namespace prefix in nodes before doing lookups (and writes?)

### ISSUE THREAD

**Issue by lsmith77** [jackalope/jackalope-doctrine-dbal#208]
Jackrabbit throws a NamespaceException when attempting to read a node with a node name that includes a namespace prefix that has not been registered.

We should also add a PHPCR API test for this.

**Comment by dbu** [comment]
is it essential to have this in the 1.2 milestone?

**Comment by dbu** [comment]
#223 handles the writing case as the NodeProcessor validates the namespace.

for reading i just created #244
