### ISSUE TITLE
do not expose UUID unless the node is referenceable

### ISSUE THREAD

**Issue by lsmith77** [jackalope/jackalope-doctrine-dbal#214]
it seems we already have some logic in place for this https://github.com/jackalope/jackalope-doctrine-dbal/blob/master/src/Jackalope/Transport/DoctrineDBAL/Client.php#L1095

however while working on some issues in PHPCR ODM we noticed that it was possible to set a UUID (this might make sense) and then search by UUID even on a non referenceable node (this results in people being able to write code where all nodes behave like referenceable nodes which can lead to problems when migrating to a different backend).

**Comment by dbu** [comment]
see https://github.com/jackalope/jackalope/pull/270

**Comment by dbu** [comment]
hm, note that the jackalope change will prevent setting a uuid on a non-referenceable node, and will never expose a uuid on them. but if you look up the uuid in the database, searching for it will still work. not sure if we should care about that at all - can't really see when this is a problem. if people do horrible hacks with the db its their own loss...
