### ISSUE TITLE
storing multivalue reference should not eliminate duplicates

### ISSUE THREAD

**Issue by dbu** [jackalope/jackalope-doctrine-dbal#222]
https://github.com/jackalope/jackalope-doctrine-dbal/blob/master/src/Jackalope/Transport/DoctrineDBAL/Client.php#L948 is doing an array_unique. i think we fixed bugs elsewhere that allowed to store the reference to the same target multiple times.

**Comment by lsmith77** [comment]
is this now fixed?

**Comment by dbu** [comment]
there is still the call to array_unique so if there is no failing test it means we are missing a test that stores the same ref multiple times. (reading, when data is loaded through fixtures probably already works)

**Comment by dbu** [comment]
the line moved to https://github.com/jackalope/jackalope-doctrine-dbal/blob/master/src/Jackalope/Transport/DoctrineDBAL/Client.php#L1001 since i created the issue. guess there is a point to link to a specific commit for these things...
