### ISSUE TITLE
fix HHVM issues with "Validation failed: no DTD found"

### ISSUE THREAD

**Issue by lsmith77** [jackalope/jackalope-doctrine-dbal#225]
https://travis-ci.org/jackalope/jackalope-doctrine-dbal/jobs/34221373

from a quick check I do not see any DTD referenced in manager.xml ..

**Comment by lsmith77** [comment]
I have opened https://github.com/facebook/hhvm/issues/5506

**Comment by dbu** [comment]
hhvm support has been dropped
