### ISSUE TITLE
Sqlite: SQLSTATE[HY000]: General error: 1 no such function: CONCAT

### ISSUE THREAD

**Issue by dantleech** [jackalope/jackalope-doctrine-dbal#249]
Am seeing this when running the CMF RoutingAutoBundle tests. Relaunching a successful build from  1 month ago also gives the same error.

https://travis-ci.org/symfony-cmf/RoutingAutoBundle/jobs/54443252#L450

This is quite strange, the call to register the CONCAT function with sqlite is being executed.

**Comment by dbu** [comment]
can you try to reproduce this in a phpcr-api-test?

**Comment by dantleech** [comment]
Regression is caused by DoctrineBundle: https://github.com/doctrine/DoctrineBundle/commit/2f8d7263c4c44445b51fc2d9bf71d21f7016347d which closes the connections on Kernel#shutdown.

See PR #250
