### ISSUE TITLE
ArrayObject-Bug in Jackalope\Transport\DoctrineDBAL\Client.php

### ISSUE THREAD

**Issue by ARoddis** [jackalope/jackalope-doctrine-dbal#253]
Since namespace is an ArrayObject now, there is the need to cast it to an array...which is done in:

   /**
     * {@inheritDoc}
     */
    public function getNamespaces()
    {
        return (array) $this->getNamespacesObject();
    }

But this is overriden by the CachedClient "getNamespaces"-Method.

Which just checks if namespaces is filled:

 /**
     * {@inheritDoc}
     */
    public function getNamespaces()
    {
        if (empty($this->namespaces)) {
            $cacheKey = 'namespaces';
            $result = $this->caches['meta']->fetch($cacheKey);
            if ($result) {
                $this->namespaces = $result;
            } else {
                $this->namespaces = parent::getNamespaces();
                $this->caches['meta']->save($cacheKey, $this->namespaces);
            }
        }
        return $this->namespaces;
    }

And if so, it justs returns its...but it is not casted there....so the engine throws a warning.

Easy fix is to cast it in the CachedClient as well...but a less "doubled" solution would be better i think. :)

Like casting it in "getNamespacePrefixes()" in the Client-Class.

**Comment by lsmith77** [comment]
could you submit a PR with the fix?

**Comment by dbu** [comment]
hm, indeed that caching logic looks broken. i think the right solution would be to change CachedClient to overwrite getNamespacesObject and cache the ArrayObject instead. otherwise we get a mess.

i consider this a blocker for 1.2.0-RC1. @ARoddis if you have time to do a PR for the change, that would be very cool indeed.

**Comment by ARoddis** [comment]
I will be able to do it today. Glad to help :)

**Comment by ARoddis** [comment]
Hmm i dont see where overriding getNamespacesObject helps...there would be still the empty ArrayObject in $this->namespaces...and CachedClient still overrides the getNamespaces()-method in the Client...getNamespacesObject in the ClientClass is using the ArrayObject already...just the CachedClient overrides the getNamespaces()-Method which leads to the problem.

And that happens because of the already present (constructor-initalized) ArrayObject in $this->namespaces. :)

There seem to bee no tests for the CachedClient...would it ok if i threw some in, just for the bug, i mean?

**Comment by dbu** [comment]
sure, tests for the CachedClient would be an excellent thing to have.

my idea was that the cached client would overwrite getNamespacesObject instead of getNamespaces and maybe use a different check to see if the namespaces are initialized or not and load them from cache if possible.

overwriting getNamespaces seems unneeded with the new code.

**Comment by ARoddis** [comment]
My fault. :D 

My mind is not that fluent before a cup of coffee...

Changed it.

Added a test specific to the bug. 

If i find time in my eastertime...i will add test for the noncache-specific logic-methods in the cached-client-tests.

**Comment by dbu** [comment]
great! can you open a pull request?

for the general test, lets best do that in a separate pull request.

**Comment by ARoddis** [comment]
Done.

Ill add the general test sperate, yea. :)

**Comment by dbu** [comment]
fixed in #256, thanks ARoddis!
