### ISSUE TITLE
\Jackalope\Transport\DoctrineDBAL\Client::$namespaces is not object

### ISSUE THREAD

**Issue by Tetragramat** [jackalope/jackalope-doctrine-dbal#284]
Hi, 
I'm using jackalope/jackalope-doctrine-dbal 1.2.1.
I got sometimes this error:
```
Call to a member function count() on a non-object
 IN FILE {myProjectDir}/vendor/jackalope/jackalope-doctrine-dbal/src/Jackalope/Transport/DoctrineDBAL/CachedClient.php
 ON LINE 103
```
That mean \Jackalope\Transport\DoctrineDBAL\Client::$namespaces is not object.
I did some research and found this: 
https://github.com/jackalope/jackalope-doctrine-dbal/blob/master/src/Jackalope/Transport/DoctrineDBAL/Client.php#L541

So if you call \Jackalope\Transport\DoctrineDBAL\CachedClient::getNamespacesObject a second time, then error appears.

Sorry for my english.

**Comment by lsmith77** [comment]
Can you look into providing a fix for this? It should be done on the 1.2 branch so that we can release a bug fix release for this.

**Comment by lsmith77** [comment]
ok .. working on this ..

**Comment by lsmith77** [comment]
can you test https://github.com/jackalope/jackalope-doctrine-dbal/pull/286 ?

**Comment by Tetragramat** [comment]
I will try test it, but it would take some time, because I cannot find when it do that.
This error apears actually only on production server and so I know only when that error was, not what for me anonymous user did.

**Comment by lsmith77** [comment]
fixed via https://github.com/jackalope/jackalope-doctrine-dbal/releases/tag/1.2.2
