### ISSUE TITLE
Copy binary data for children nodes

### ISSUE THREAD

**Issue by rederrik** [jackalope/jackalope-doctrine-dbal#294]
Hi,
In \Jackalope\Transport\DoctrineDBAL\Client:copyNode() line 698 we execute [query](https://github.com/jackalope/jackalope-doctrine-dbal/blob/master/src/Jackalope/Transport/DoctrineDBAL/Client.php#L698) to copy binary data, but according to update params we are trying to copy the same data every iteration 
>WHERE b.node_id =  ? [$srcNodeId]

since $srcNodeId is id of the root source node, not current iteration children node.

Is this by mistake or is this intended?

**Comment by lsmith77** [comment]
yeah this looks like a bug to me as well

**Comment by dbu** [comment]
it would be awesome if you can write a failing test in
https://github.com/phpcr/phpcr-api-tests/blob/master/tests/Writing/CopyMethodsTest.php
and then fix. that way we know there really was a problem and we also
know its fixed and will stay fixed...

do you have time to look into that @rederrik? we are of course here to
help you getting set up if needed.

**Comment by rederrik** [comment]
Sure, the fix seems to be easy enough.
So I need to make 2 pull requests - 1 for this repo and one for tests repo, right?

**Comment by dbu** [comment]
great! exactly, needs two separate pull requests. if you `composer
update --prefer-source`, you can develop the test bit inside the vendor
folder (if you already have the code as non-git checkout just remove
vendor/phpcr/phpcr-api-tests first.

**Comment by rederrik** [comment]
#297 and https://github.com/phpcr/phpcr-api-tests/pull/167 to fix it.

**Comment by dbu** [comment]
very cool, thanks a lot for working on this!
