### ISSUE TITLE
Broken Link in Readme

### ISSUE THREAD

**Issue by andylibrian** [jackalope/jackalope-doctrine-dbal#301]
I spotted a broken link in README.md

> See [PHPCR Tutorial](https://github.com/phpcr/phpcr-docs/blob/master/tutorial/Tutorial.md) for a more detailed tutorial on how to use the PHPCR API.

Where should the link go to?

**Comment by dantleech** [comment]
Probably: http://phpcr.readthedocs.org/en/latest/book/index.html /cc
@dbu

**Comment by dbu** [comment]
indeed, thanks for reporting the mistake! fixed in 59bfba8
