### ISSUE TITLE
Property-Type - required type wrong data-type

### ISSUE THREAD

**Issue by wachterjohannes** [jackalope/jackalope-doctrine-dbal#313]
I have following problem in sulu.

We have defined a custom node-type with a custom property definition which will be persisted in the database.

When we now try to save a node with the custom node-type the client fetches the definition from the database and converts them into a array of data.

Afterwards this array will be used to set default values. In this stacktrace also the `PropertyType::valueFromName` will be called. This function throws an exception because of a wrong dataformat of the given type. This type should be an integer because then the other function `PropertyType::nameFromValue` would be called.

important code-parts:

* https://github.com/jackalope/jackalope-doctrine-dbal/blob/master/src/Jackalope/Transport/DoctrineDBAL/Client.php#L2029
* https://github.com/phpcr/phpcr/blob/master/src/PHPCR/PropertyType.php#L270
* https://github.com/phpcr/phpcr/blob/master/src/PHPCR/PropertyType.php#L223
* https://github.com/jackalope/jackalope/blob/master/src/Jackalope/NodeType/NodeProcessor.php#L204

I will create a pull-request tomorrow. which would force the type (int) in the Client of doctrine-dbal https://github.com/jackalope/jackalope-doctrine-dbal/blob/master/src/Jackalope/Transport/DoctrineDBAL/Client.php#L2029

**Comment by dbu** [comment]
fixed in #314

**Comment by dbu** [comment]
thanks johannes!

**Comment by wachterjohannes** [comment]
thanks for fase response (:
