### ISSUE TITLE
ID of document does not seem updated in postUpdate event

### ISSUE THREAD

**Issue by richard-fizz** [jackalope/jackalope-doctrine-dbal#320]
For instance, if I flush my updated document to the document manager and assign a postUpdate event to it, the node name and all other properties change, but the id stays the same.
This makes for difficult situations when integrating with systems such as Elastica, since it needs an updated id for it to work.

**Comment by dbu** [comment]
this sounds like the issue belongs to https://github.com/doctrine/phpcr-odm/ - jackalope does neither have documents nor events... can you please open an issue over there to continue the discussion?

is the id updated once the flush operation is finished? is it just a timing issue? or is the id not updated at all?

**Comment by richard-fizz** [comment]
Ah, thought the events were being dispatched by Jackalope :) I'll open an issue there.
