### ISSUE TITLE
Should throw WorkspaceNotFoundException if workspace doesn't exist.

### ISSUE THREAD

**Issue by dantleech** [jackalope/jackalope-doctrine-dbal#322]
If you attempt `$session->getRootNode()` on Jackrabbit when the workspace does not exist but you receive a `WorkspaceNotFoundException`, on Doctrine-Dbal you get `PathNotFoundException`.

It is thrown [here](https://github.com/jackalope/jackalope-doctrine-dbal/blob/poc_phpbench/src/Jackalope/Transport/DoctrineDBAL/Client.php#L1271) which throws a `PathNotFoundException` is there are no query results - which does not give an indication as to if the workspace exists or not.

**Comment by dbu** [comment]
i guess this happens only if checking for workspace existence is disabled. we could trigger the workspace existence check on the fist not found exception (but cache the result in case several path not found are triggered)
