### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by bigfoot90** [jackalope/jackalope-doctrine-dbal#328]
I'm facing with ```Error 500``` when i browse into the second depth level.

From my project's symfony console I can view the paths:
```
$ cons doctrine:phpcr:node:dump --depth 2
ROOT:
  cms:
    pages:
    routes:
    content:
    menu:
```

While in your phpcr-browser I can see only the root path
![image](https://cloud.githubusercontent.com/assets/4598274/14289717/516b1d14-fb5c-11e5-848c-aff4b0dd9fd0.png)

Please tell me how can I inspect the problem.
Thanks

**Comment by dbu** [comment]
hi,
do you mean the https://github.com/marmelab/phpcr-browser/ ? if its that one, you best open the issue in that repository, as its likely not a problem of jackalope but of the client.
btw, there also exists the phpcr-shell which is more convenient than the node:dump command. its a bit like the mysql and postgres command line clients, even supporting UPDATE statements to manipulate data.

**Comment by bigfoot90** [comment]
Yes, sorry.
