### ISSUE TITLE
Cloning nodes does not retain the order of children

### ISSUE THREAD

**Issue by syeo66** [jackalope/jackalope-doctrine-dbal#330]
When using something like

`$documentManager->getPhpcrSession()->getWorkspace()->copy($object->getId(), $destPath);` 

(using Symfony/PHPCR ODM) the ordering of children is getting all mixed up.

The ordering of children in my tree in the original document:
![original](https://cloud.githubusercontent.com/assets/1178021/21094182/f59b9d8c-c055-11e6-80a0-609b7231f765.png)

and the clone:
![clone](https://cloud.githubusercontent.com/assets/1178021/21094189/ff52c95e-c055-11e6-844e-e2a41778d5e4.png)

Am I missing something?

**Comment by dantleech** [comment]
This seems like a bug, you could start by adding an `ORDER BY depth, sort_order` here:

https://github.com/jackalope/jackalope-doctrine-dbal/blob/master/src/Jackalope/Transport/DoctrineDBAL/Client.php#L622

And see where that gets you -- if that works it would be great to add a test in the PHPCR test suite. (https://github.com/phpcr/phpcr-api-tests)

**Comment by syeo66** [comment]
Thanks, `ORDER BY depth, sort_order` seems to fix this. I'll see if I find the time to write a test... however it does not look good atm.

**Comment by dbu** [comment]
@syeo66 if you find time to do the code change without a test it would already be an improvement. if the order matters, it can't get worse with that, only better, as the order is currently undefined. i guess we normally just get lucky, or order did not matter in the cases.

**Comment by dbu** [comment]
fixed in #333
