### ISSUE TITLE
avoid using deprecated PDO:: constants in calls to doctrine dbal

### ISSUE THREAD

**Issue by dbu** [jackalope/jackalope-doctrine-dbal#355]
according to the [upgrade notes](https://github.com/doctrine/dbal/blob/master/UPGRADE.md#upgrade-to-27), we should stop using the pdo constants and instead use the FetchMode constants from dbal.

we should figure out the lowest dbal version that supports those dbal constants and adjust the dbal dependency accordingly.

**Comment by Majkl578** [comment]
> we should figure out the lowest dbal version that supports those dbal constants

2.7.0 via https://github.com/doctrine/dbal/pull/2996.

**Comment by dbu** [comment]
i started on this in #357 - @Majkl578 would you know an answer to the question i have there?

**Comment by dbu** [comment]
fixed in https://github.com/jackalope/jackalope-doctrine-dbal/pull/373
