### ISSUE TITLE
Option 'jackalope.check_login_on_server' => false is ignored / discarded

### ISSUE THREAD

**Issue by holtkamp** [jackalope/jackalope-doctrine-dbal#358]
When trying to improve performance, and reduce the amount of initial queries, I noticed setting `'jackalope.check_login_on_server' => false` during initialization does not make a lot of difference since Client::assertLoggedIn() sets the value to `true` again. 

https://github.com/jackalope/jackalope-doctrine-dbal/blob/d810fd88237d7537c431c38005150db1c1f9d8a3/src/Jackalope/Transport/DoctrineDBAL/Client.php#L511

**Comment by dbu** [comment]
the intention of this option is to make jackalope more lazy, so it only does those things when its actually needed. if you actually run queries, the "overhead" of the extra query on the workspaces table seemed negligible to us, compared to random weird errors if the workspace does not exist and we query for nodes in that workspace.

**Comment by holtkamp** [comment]
Aah, ok, thanks for the clarification. Seems to be related with https://github.com/thephpleague/flysystem-phpcr/issues/10

the adapter always loads the root node, so the checkLoginOnServer will always be done as well.

Closing issue.
