### ISSUE TITLE
Issue with doctrine/doctrine-bundle 2.6

### ISSUE THREAD

**Issue by alexislefebvre** [jackalope/jackalope-doctrine-dbal#397]
I don't use this bundle personally but an issue arised in a bundle I maintain:

> TypeError: Argument 1 passed to Jackalope\Transport\DoctrineDBAL\Client::registerSqliteFunctions() must be an instance of PDO, instance of Doctrine\DBAL\Logging\Connection given, called in /home/runner/work/LiipTestFixturesBundle/LiipTestFixturesBundle/vendor/jackalope/jackalope-doctrine-dbal/src/Jackalope/Transport/DoctrineDBAL/Client.php on line 2877

[source](https://github.com/liip/LiipTestFixturesBundle/runs/5780590715?check_suite_focus=true)

See these explanations about the new logging added in Doctrine that affected LiipTestFixturesBundle too: https://github.com/liip/LiipTestFixturesBundle/issues/154#issuecomment-1083185687 and https://github.com/liip/LiipTestFixturesBundle/issues/154#issuecomment-1085248596

**Comment by dbu** [comment]
fixed in #398
