### ISSUE TITLE
switch to PSR cache

### ISSUE THREAD

**Issue by dbu** [jackalope/jackalope-doctrine-dbal#411]
doctrine/cache 1 is EOL, and cache 2 is a transitional package.

we should use PSR cache directly in CachedClient. See #408 for more context.

**Comment by alexander-schranz** [comment]
I'm totally fine to switch complete to PSR Cache for 2.0 👍  What I'm not sure if with the merge of #408 the jackalope integration know will always error when using `doctrine/cache:^2.0` in dev as there always the ArrayCache was used if I remember 🤔 . But need first check @sulu to get rid of doctrine/cache ^1.0.

**Comment by derrabus** [comment]
For Doctrine's packages, we've added support for PSR-6 caches in a minor release and switched all internal logic to PSR-6 already. If an app configures a Doctrine cache, we wrap it into a PSR-6 adapter and issue a deprecation. On the next major of such a package, we drop the support for Doctrine Cache completely. This allows a smooth transition of downstream code.

**Comment by dbu** [comment]
i realized that i already switch to psr cache for jackalope 2 quite a while ago in #382. i have now adjusted the 1.x cache client to support psr cache too in #413 , so that people wanting to support either jackalope 1 or 2 (e.g. the symfony bundle) can already switch to psr cache.
