### ISSUE TITLE
Exception Error after upgrading to 1.10.0

### ISSUE THREAD

**Issue by hual7** [jackalope/jackalope-doctrine-dbal#428]
Hi,
after upgrading to 1.10.0 I get errors in productive mode.

request.CRITICAL: Uncaught PHP Exception Error: "Attempt to assign property ":jcr:path" on null" at /var/www/vendor/jackalope/jackalope-doctrine-dbal/src/Jackalope/Transport/DoctrineDBAL/CachedClient.php line 346 {"exception":"[object] (Error(code: 0): Attempt to assign property \":jcr:path\" on null at /var/www/vendor/jackalope/jackalope-doctrine-dbal/src/Jackalope/Transport/DoctrineDBAL/CachedClient.php:346)"} []

php.CRITICAL: Uncaught Error: Attempt to assign property ":jcr:path" on null {"exception":"[object] (Error(code: 0): Attempt to assign property \":jcr:path\" on null at /var/www/vendor/jackalope/jackalope-doctrine-dbal/src/Jackalope/Transport/DoctrineDBAL/CachedClient.php:346)"} []

App is running on Debian 10, MariaDB 10.5.21, Symfony 6.3.8, Sulu 2.5.10

**Comment by chirimoya** [comment]
#429 can you test? ;-)

**Comment by hual7** [comment]
> #429 can you test? ;-)

looks good ;-)

**Comment by dbu** [comment]
sorry about that one. we seem to not have any functional tests that hit the cache in the client or the CI would have told us.

fixed in https://github.com/jackalope/jackalope-doctrine-dbal/releases/tag/1.10.1
