### ISSUE TITLE
Add compatibility with doctrine/dbal 4

### ISSUE THREAD

**Issue by garak** [jackalope/jackalope-doctrine-dbal#441]

**Comment by garak** [comment]
Sorry, I just noticed there's an open PR about it.
I often forget to check for both open issues *and* PRs (even if to me, in perfect world, there should be only PRs linked to issues)

Feel free to close this, if it makes sense.

**Comment by dbu** [comment]
lets keep this for others who check issues but not the PRs :-)

i marked the PR as fixing the issue...
