### ISSUE TITLE
Error inside the transport layer: Cache key 'nodes by uuid: 9ec4d67b-74e2-428a-a824-8f927e37749d, default' contains reserved characters '{}()/@:'.

### ISSUE THREAD

**Issue by Johann0290** [jackalope/jackalope-doctrine-dbal#450]
Hi together. Jackalope appears to have a bug in the production environment. This definitely occurs also in the version 2.0.1. Only in production, the function ClearNodeCache in CachedClient.php is called. In line 105, the cacheKey is set again without subsequently calling the sanitizeKey function. This leads to the error "Error inside the transport layer: Cache key 'nodes by uuid: 9ec4d67b-74e2-428a-a824-8f927e37749d, default' contains reserved characters '{}()/@:'.". The assigned string contains a ":".

**Comment by dbu** [comment]
thanks for the clear report. indeed that place seems to have been missed when adding the key sanitize logic. fixed in #451 and tagged as https://github.com/jackalope/jackalope-doctrine-dbal/releases/tag/2.0.2

**Comment by Johann0290** [comment]
Gladly. I also appreciate the quick fix.
